In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt


In [2]:
d = datasets.load_breast_cancer()
x, y = d.data, d.target

In [3]:
x

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
x.shape

(569, 30)

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
y.shape

(569,)

In [7]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=1234)

In [8]:
class LogisticRegression:

    def __init__(self, learning_rate=0.001, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        
        n_samples, n_features = X.shape

        # init parameters
        self.weights = np.zeros(n_features)
        self.bias = 0

        # gradient descent
        for _ in range(self.n_iters):
            # approximate output variable (y) with linear combination of weights and x, plus bias
            linear_model = np.dot(X, self.weights) + self.bias
            # apply sigmoid function
            y_predicted = self._sigmoid(linear_model)
            print(y_predicted)
            # compute gradients
            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y)) #derivative w.r.t weights
            db = (1 / n_samples) * np.sum(y_predicted - y)  #derivative w.r.t bias
            # update parameters
            self.weights -= self.lr * dw
            self.bias -= self.lr * db

            
        
    def predict(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        y_predicted = self._sigmoid(linear_model)
        y_predicted_cls = [1 if i > 0.5 else 0 for i in y_predicted]
        return np.array(y_predicted_cls)

    def _sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
def accuracy(y_true, y_pred):
    accuracy = np.sum(y_true == y_pred) / len(y_true)
    return accuracy

In [9]:
itr=[]
acc=[]

In [10]:
xtrain

array([[1.288e+01, 1.822e+01, 8.445e+01, ..., 1.096e-01, 2.582e-01,
        8.893e-02],
       [1.113e+01, 2.244e+01, 7.149e+01, ..., 6.413e-02, 3.169e-01,
        8.032e-02],
       [1.263e+01, 2.076e+01, 8.215e+01, ..., 1.105e-01, 2.226e-01,
        8.486e-02],
       ...,
       [1.247e+01, 1.860e+01, 8.109e+01, ..., 1.015e-01, 3.014e-01,
        8.750e-02],
       [1.822e+01, 1.870e+01, 1.203e+02, ..., 1.325e-01, 3.021e-01,
        7.987e-02],
       [1.272e+01, 1.378e+01, 8.178e+01, ..., 6.343e-02, 2.369e-01,
        6.922e-02]])

In [11]:

regressor = LogisticRegression(learning_rate=0.0001, n_iters=1000)
regressor.fit(xtrain, ytrain)
predictions = regressor.predict(xtest)
itr.append(1000)

[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.

 9.99440806e-01 9.99999931e-01 9.99999980e-01]
[6.18216173e-012 5.67906584e-005 1.80364958e-005 1.46433657e-021
 3.20255734e-003 8.94948414e-013 2.59601692e-004 2.98882242e-012
 6.37619641e-006 2.56606328e-005 5.35882944e-052 2.06108177e-009
 1.93952659e-019 1.79213435e-023 5.57947933e-005 1.05936291e-002
 8.96951372e-014 8.42309990e-008 2.32906747e-110 2.86042924e-007
 2.37162517e-018 2.50740697e-009 4.69428147e-011 2.48655245e-011
 4.53329992e-005 9.49374463e-013 2.02465794e-002 6.09206630e-032
 5.58142124e-017 3.80964854e-010 2.32966289e-014 3.29973814e-009
 3.35334814e-011 4.21076777e-010 1.04898013e-018 3.16740049e-015
 4.44695849e-008 4.86490493e-006 2.16170868e-030 1.10337538e-005
 5.84260741e-006 2.20313881e-012 2.20584134e-010 3.43694627e-032
 2.41070262e-071 3.10477137e-011 6.88860245e-009 7.09975442e-011
 2.25375466e-036 5.34539036e-007 1.59559581e-006 9.16757295e-021
 2.14183880e-005 1.55899777e-009 3.73964350e-007 2.28372917e-006
 1.43319867e-014 5.73919765e-005 5.02901975

[5.81592324e-010 1.49333330e-001 3.60367189e-001 1.89653301e-023
 9.43288485e-001 1.96079549e-007 5.83639461e-001 1.47549200e-009
 8.24445516e-003 4.67870979e-002 1.18098125e-058 2.63207951e-005
 1.27092599e-019 1.05439362e-020 6.48210646e-002 4.87576535e-001
 2.87769197e-010 5.70073083e-004 3.91628780e-139 1.25608693e-004
 1.06678259e-016 3.05450717e-005 2.91049044e-008 1.40622887e-007
 3.59542118e-002 6.54468455e-011 9.80048877e-001 6.44278276e-025
 8.37191041e-016 4.53187521e-004 6.61605264e-013 2.86978180e-006
 1.18132657e-005 1.28874837e-006 4.32508926e-017 2.14252415e-013
 1.20151838e-005 9.37425980e-003 3.23811611e-028 1.58019849e-003
 9.51819975e-003 1.64031082e-005 1.19907269e-005 1.77156891e-030
 7.00187273e-086 2.59813509e-007 1.45701228e-006 3.66854676e-008
 2.40732366e-038 1.89444764e-004 7.16698389e-003 6.02425792e-020
 1.14162921e-001 2.54468858e-005 2.39694457e-003 3.07308220e-002
 5.37519660e-010 2.89861714e-003 1.65274450e-005 3.83751187e-019
 2.62253858e-019 5.484959

[1.00205770e-003 9.99863253e-001 9.99995150e-001 3.13551529e-016
 9.99994896e-001 9.95270264e-001 9.99978763e-001 1.11292719e-002
 9.97686170e-001 9.99505732e-001 2.17803208e-043 9.93996325e-001
 4.58838596e-012 1.98945165e-009 9.99317017e-001 9.97152674e-001
 3.36063473e-002 9.98113726e-001 2.12910536e-117 9.08493678e-001
 3.21879757e-008 9.94442753e-001 8.42311089e-002 7.43920021e-001
 9.98327113e-001 2.16569752e-004 9.99992864e-001 1.97630302e-007
 4.22125008e-008 9.99993864e-001 4.50532435e-006 7.01561919e-001
 9.99744949e-001 8.48290862e-001 1.80866887e-008 5.42066783e-006
 5.90961078e-001 9.98632424e-001 9.51751493e-015 9.06732241e-001
 9.98296753e-001 9.99991611e-001 9.98134454e-001 1.29270460e-016
 1.06011253e-068 8.09019544e-001 2.15306135e-001 6.82257909e-002
 1.71073882e-025 9.06867935e-001 9.99437480e-001 4.30305663e-011
 9.99923277e-001 9.95513146e-001 9.99120370e-001 9.99924842e-001
 3.73390361e-001 8.30430719e-001 6.95090936e-001 6.05905287e-011
 1.20523384e-008 9.999700

[9.99748754e-01 9.99999994e-01 1.00000000e+00 1.81860943e-07
 9.99999999e-01 1.00000000e+00 9.99999999e-01 9.99993578e-01
 9.99999934e-01 9.99999979e-01 4.47040698e-24 9.99999999e-01
 2.29235670e-03 9.99651912e-01 9.99999946e-01 9.99988529e-01
 9.99999855e-01 9.99999997e-01 1.11691001e-84 9.99998671e-01
 9.83094703e-01 9.99999999e-01 9.99997697e-01 9.99999985e-01
 9.99999838e-01 9.99486354e-01 9.99999993e-01 1.00000000e+00
 9.28058137e-01 1.00000000e+00 9.91595806e-01 9.99999534e-01
 1.00000000e+00 9.99999960e-01 9.79862646e-01 9.98047888e-01
 9.99995035e-01 9.99999972e-01 8.68551327e-01 9.99981921e-01
 9.99999957e-01 1.00000000e+00 1.00000000e+00 2.52359599e-01
 4.43036051e-45 9.99999985e-01 9.99985542e-01 9.99995421e-01
 3.03465387e-10 9.99997921e-01 9.99999996e-01 2.57722856e-01
 9.99999998e-01 9.99999999e-01 9.99999997e-01 1.00000000e+00
 9.99999999e-01 9.99878608e-01 9.99997153e-01 9.06583895e-02
 9.99719740e-01 9.99999998e-01 9.99639865e-01 9.99992495e-01
 9.99995302e-01 9.995363

[9.97156024e-01 9.99999973e-01 1.00000000e+00 1.08318233e-08
 9.99999996e-01 1.00000000e+00 9.99999994e-01 9.99878088e-01
 9.99999700e-01 9.99999915e-01 4.17387323e-28 9.99999975e-01
 8.03511847e-05 8.69934466e-01 9.99999808e-01 9.99985933e-01
 9.99994089e-01 9.99999966e-01 1.40152163e-90 9.99993207e-01
 5.03989851e-01 9.99999977e-01 9.99967232e-01 9.99999640e-01
 9.99999421e-01 9.94426333e-01 9.99999983e-01 9.99999774e-01
 3.58079842e-01 1.00000000e+00 8.84313081e-01 9.99995930e-01
 1.00000000e+00 9.99999375e-01 4.73168546e-01 9.51043067e-01
 9.99973902e-01 9.99999854e-01 2.85216509e-03 9.99934062e-01
 9.99999778e-01 1.00000000e+00 9.99999998e-01 1.26298255e-04
 2.00616968e-49 9.99999412e-01 9.99900531e-01 9.99928078e-01
 2.90655290e-13 9.99990532e-01 9.99999977e-01 5.50114710e-03
 9.99999992e-01 9.99999986e-01 9.99999970e-01 9.99999997e-01
 9.99999846e-01 9.99734777e-01 9.99985356e-01 1.37863837e-03
 9.23576937e-01 9.99999991e-01 9.98288291e-01 9.99930097e-01
 9.99955108e-01 9.940095

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



[9.51258829e-01 9.99998628e-01 9.99999830e-01 2.58403226e-07
 9.99999752e-01 9.99912050e-01 9.99999425e-01 9.76762881e-01
 9.99990798e-01 9.99997657e-01 9.71270742e-30 9.99942908e-01
 2.25942129e-05 6.46315805e-05 9.99996378e-01 9.99990340e-01
 9.83809586e-01 9.99982622e-01 2.49248415e-80 9.99890342e-01
 3.31382559e-03 9.99967064e-01 9.96037541e-01 9.99444084e-01
 9.99989639e-01 9.57337116e-01 9.99999349e-01 4.35954048e-07
 5.34584180e-02 9.99999095e-01 4.00965870e-01 9.99803707e-01
 9.99968549e-01 9.99768650e-01 6.09266292e-03 2.01533817e-01
 9.99727250e-01 9.99992442e-01 1.56583474e-09 9.99261933e-01
 9.99988210e-01 9.99955401e-01 9.99966533e-01 1.71125195e-10
 1.24594018e-45 9.87891299e-01 9.98169093e-01 9.84746247e-01
 1.63678762e-15 9.99886233e-01 9.99997789e-01 8.33926222e-05
 9.99998998e-01 9.99968584e-01 9.99985365e-01 9.99998041e-01
 9.47637533e-01 9.99573710e-01 9.99848928e-01 5.24295763e-06
 1.97987775e-04 9.99999537e-01 9.94017343e-01 9.97406567e-01
 9.98614753e-01 9.358789

In [7]:

print("LR classification accuracy:", accuracy(ytest, predictions))
acc.append(accuracy(ytest, predictions))

LR classification accuracy: 0.9298245614035088
